export {default as LoginPage} from './login'
export {default as AuthLayout} from './AuthLayout'
export {default as RegisterPage} from './Register'
export {default as ForgetPasswordPage} from './forget-password'
export {default as ResetPasswordPage} from './reset-password'
export {default as VerifyOTPPage} from './verifyEmail'
export {default as PageNotFound} from './PageNotFound'
